### ISSUE TITLE
Strings in NXmx - H5T_VARIABLE?

### ISSUE THREAD

**Issue by fleon-psi** [HDRMX/NXmx#7]
Is there a preference how strings should be written in NXmx HDF5 - fixed length or with H5T_VARIABLE? Should both options be supported by software? Thanks for clarification!

**Comment by yayahjb** [comment]
Dear Filip,
  Variable length strings do work, but they are a royal pain for a lot of
software packages.  For maximal portability,
I would recommend fixed length strings, using the C-style null termination
and padding (my first choice), or
fortran style blank termination and padding, and adopting the input
processing practice of always stripping trailing nulls
and blanks.  The other portability action is to convert all incoming common
line terminations:  \n, \r, \z, \r\n to \n.
  Regards,
    Herbert

**Comment by fleon-psi** [comment]
Dear Herbert, 
Thank you very much for answering - I will therefore refrain from using H5T_VARIABLE in my code.
Best,
Filip

**Comment by yayahjb** [comment]
Very sensible
